[project]
name = "videos"
version = "0.1.0"
description = "Environment to generate manim videos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
    "seaborn>=0.13.2,<0.14.0",
]

[tool.uv]